### ISSUE TITLE
Cannot create custom url path to the existing destination

### ISSUE THREAD

**Issue by Pepewitch** [thangman22/short-fire#5]
# Current firebase.json
Have only 1 path to /TypeScript-React-Starter/issues/12
<img width="757" alt="screen shot 2562-02-22 at 12 49 37" src="https://user-images.githubusercontent.com/28859131/53222491-98ef5600-36a0-11e9-8e91-a02251519e08.png">

# Test
Create a new path name "ts-react-issue"
<img width="1203" alt="screen shot 2562-02-22 at 12 49 53" src="https://user-images.githubusercontent.com/28859131/53222594-e8358680-36a0-11e9-99a7-1037bddb60bb.png">

# Expect
Should it create a new path to the existing destination instead of deny the user input and return the old existing path?

**Comment by thangman22** [comment]
This use case is based on duplicate creation problem. We need to discuss more 2 use case.

How to handle slug when the user defines the slug.
How to handle slug when the user did not define a slug.

What is the expectation of each?

**Comment by Pepewitch** [comment]
1) User defines slug, the system should create a new path which matches the input slug.

2) User does not define slug, the system should return the existing path.
I think it is okay to return the existing path with slug.
If user needs a new random path, then it should have an option for him to force the system to create a new random string path for the user like..
```
short-fire --new <url>
```

**Comment by thangman22** [comment]
Can you open pull request?

**Comment by thangman22** [comment]
Close by PR
